JuliaAI/MLJ.jl

README.md

Changed the git url. Solves #23

Update the git link in readme

---

CONTRIBUTE.md

Churvay -> [Churavy](https://github.com/vchuravy)

Typo fix in contribute

---

src/loading.jl

I was trying to turn `@load` into a regular function, but there are a couple of tricky bits:
* it isn't straightforward to get the module of the caller place (the information should be in `stacktrace()`, see https://discourse.julialang.org/t/get-module-of-a-caller/11445/3, but the level of the stack where the caller is may not be easy to determine),
* the argument would need to be a string or a `Symbol`
In the end, I think the easiest thing is to leave it as a macro.

Simplify methods of load macro by reducing code duplication

---

src/loading.jl
test/loading.jl

Fixed the PR as discussed in #195 
Fixes: #192

Fix #192: Add verbosity option to @load macro

---

docs/Project.toml

To fix documentation fail on master

add DecisionTree="0.8" to documentation [compat]

---

docs/src/machines.md

manual change #251

---

docs/src/composing_models.md

closes #267

---

.travis.yml
CONTRIBUTING.md
Project.toml
docs/Project.toml
src/ensembles.jl
src/machines.jl
src/networks.jl
test/networks.jl

#245 
This PR will fail travis tests until:

Remove caps on CategoricalArrays and DecisionTrees

---

Project.toml

Will merge once https://github.com/JuliaRegistries/General/pull/4881 is in

bumping compats for MLJBase and MLJModels

---

docs/src/evaluating_model_performance.md
src/resampling.jl
test/resampling.jl

Allow resampling strategies to look at data

---

docs/src/common_mlj_workflows.md
docs/src/mlj_cheatsheet.md
docs/src/model_search.md

manual corrections #340

---

src/networks.jl
test/composites.jl

Minor  commits to remove a warning

Warning removal

---

README.md

comment: would such functionality be best implemented inside MLJ or as part of an MLJEnsembles?

Readme: add boosting in wanted

---

docs/src/adding_models_for_general_use.md

Some instructions for adding model to registry

---

src/machines.jl

typo fix in warning

---

.travis.yml
src/MLJ.jl

exports table (from mljbase) + add 1.3 in travis

---

src/MLJ.jl
src/machines.jl
src/networks.jl
src/tuning.jl
test/tuning.jl

- Minor issue with `learning_curve!`: the operation kwarg was not being passed to the resampler.
- Address #377

Learning curve again

---

src/resampling.jl

Tweak shuffle logic in resampling strategy constructors 

---

src/resampling.jl

Updated docstring of `Holdout` struct.

Updated docstring of Holdout struct.

---

src/scitypes.jl

replace Val{:mlj} -> ScientificTypes.MLJ to resolve #413

---

Project.toml

Extend [compat] StatsBase = "^0.32,^0.33"

---

Project.toml
README.md
docs/src/tuning_models.md

Readme update 

---

Project.toml
docs/src/machines.md

Fix bug in defining MLJ_VERSION (#508 PR #509)

For a 0.11.2 release

---

src/MLJ.jl

clean up: remove no longer defined exports

---

Project.toml
README.md
docs/make.jl
docs/src/common_mlj_workflows.md
docs/src/getting_started.md
docs/src/index.md
docs/src/julia_blogpost.md
material/MLJLogo2.svg
src/MLJ.jl
test/ensembles.jl

Export make_moons, etc; re-organize documentation

---

docs/src/index.md

update tutorial link

---

README.md
docs/src/index.md

Binder button added in README.md and a link in the index.md file in the documentation.

links to mybinder.org added

---

paper/paper.md

remove deprecated kind=... syntax from paper.md

paper.md edit . No release

---

docs/src/transformers.md

switch to new @from_network synthax in docs

---

docs/src/adding_models_for_general_use.md

corrects wrong method signatures in docs

corrected wrong method signatures in docs

---

docs/src/adding_models_for_general_use.md
docs/src/quick_start_guide_to_adding_models.md

Discourage Union types for fields

---

.github/workflows/CompatHelper.yml

This pull request installs CompatHelper on the MLJ.jl repository.

Install CompatHelper on this repository

---

docs/src/index.md

tweak lightning tour to avoid model/machine confusion

---

docs/src/composing_models.md
docs/src/working_with_categorical_data.md

Documentation updates. No new release.

---

docs/src/adding_models_for_general_use.md
docs/src/machines.md

https://github.com/alan-turing-institute/MLJBase.jl/pull/429

Update manual for new serialization API. No release

---

paper/paper.bib

* Weird `<200>` char removed from `paper.bib`
* References in `paper.bib` formatted and `adurl` replaced by `url`

Paper references

---

paper/paper.bib
test/runtests.jl

https://github.com/alan-turing-institute/MLJNearestNeighborsInterface.jl/issues/1

Suspend EnsembleModel testing

---

docs/src/tuning_models.md

Reverts alan-turing-institute/MLJ.jl#697

Revert "Added latin_hypercube docs"

---

Project.toml
docs/Project.toml
src/MLJ.jl

#784 
Also, re-export BinaryThresholdPredictor

For a 0.16.4 release

---

docs/make.jl
docs/src/getting_started.md
docs/src/weights.md

Improve docs re weights

---

docs/src/adding_models_for_general_use.md

Document hyper-parameter access required for models

---

ORGANIZATION.md
ROADMAP.md
docs/src/getting_started.md
docs/src/list_of_supported_models.md

Broken link fixes in docs. No new release. 

---

examples/lightning_tour/Manifest.toml
examples/lightning_tour/lightning_tour.ipynb
examples/lightning_tour/lightning_tour.jl
examples/lightning_tour/lightning_tour.md

Does not trigger a new release.

Update examples/lightning_tour/ for MLJ 0.17

---

docs/src/common_mlj_workflows.md

Documentation fix. No new release

---

docs/src/composing_models.md

Tweak docs for nodes

---

Project.toml
src/MLJ.jl

For a 0.18.2 release

---

src/MLJ.jl

Re-export `default_scitype_check_level`

---

docs/src/composing_models.md
docs/src/homogeneous_ensembles.md

Clarify homogeneous ensembles comments

---

docs/src/third_party_packages.md

Finally addressing [this](https://github.com/alan-turing-institute/MLJ.jl/issues/967).

added to docs

---

docs/src/list_of_supported_models.md

updating Clustering.jl model list to address #1000

---

docs/src/adding_models_for_general_use.md

Clarify data front-end in docs

---

.github/workflows/ci.yml
docs/make.jl

- Attempt to fix #1007 
I haven't tested this locally, it works if CI fails

Make docs fail on error

---

ROADMAP.md

I had a difficulty of understanding the `Avoid common pain points of the other frameworks` section of the ROADMAP.md so I asked to Julia slack channel.
I thought the list contained things to stay away in development so it got me confused.
There, they explained to me every element of the list and after that, I understood it.
Now, I thought it can get other potential contributors confused and proposed a better wording from my understanding. I hope it resembles the ideas of the MLJ.

feat: Update ROADMAP.md be more understandable

---

docs/make.jl

Try to deploy docs again x 3

---

Project.toml

Move EvoLinear into [extras] where it belongs

---

docs/src/common_mlj_workflows.md
docs/src/mlj_cheatsheet.md

To resolve #1108 
cc @EssamWisam

Update cheatsheet and workflow docs

---

docs/src/mlj_cheatsheet.md

Adds some minor corrections, clarifications, and simplifications. Some longer lines will now be shorter. 
cc @EssamWisam

Tweak the cheatsheet again

---

docs/make.jl
docs/src/logging_workflows.md

Update doc page for third party logging platforms
