README.md
doc/tiny_demo.ipynb

in partition, should be 0.7 for a 70:30 split. 
(it changes the RMS for subsequent results quoted, though there's randomness anyway so it doesn't matter too much I guess)

minor typo fix in readme

---

README.md

error if install according to old version:
```julia
ERROR: Unsatisfiable requirements detected for package MLJBase [a7f614a8]:
MLJBase [a7f614a8] log:
├─MLJBase [a7f614a8] has no known versions!
└─restricted to versions * by MLJ [add582a8] — no versions left
└─MLJ [add582a8] log:
├─possible versions are: 0.1.0 or uninstalled
└─MLJ [add582a8] is fixed to version 0.1.0
```

updated install guide (MLJBase first)

---

src/interfaces/Clustering.jl

`k`,  should be at least equal to 2 and not `1`, mixup with knn. (see also https://github.com/JuliaStats/Clustering.jl/blob/master/src/kmeans.jl#L31).

fix for the clean! method of kmeans

---

src/MLJ.jl
src/tasks.jl
test/tasks.jl

Address first part of #109.  I've added basic tests, but they can probably be improved.

Add type coercion for vectors and columns

---

test/tasks.jl

The operator `<:` effectively acts like a subset operator, hence
```julia
julia> Count <: Union{Missing, Count}
true
```
For this reason, testing something like `scitype_union(x) <: Union{Count, Missing}` would fail to catch the case in which the missing values are lost somehow.
I [did this](https://github.com/giordano/MLJ.jl/commit/4f2e916c6c52d6fbe20f4a158962b3412cbf1524#diff-c2e14b5f3722eef92f44eecba69b7cd8) for the `Continuous` and `Count` case, but forgot to use the same test for discrete case.

Fix tests about Union{Missing, ...}

---

.travis.yml
docs/Project.toml

I'd argue that we should not be using `master` for `MLJBase` and `MLJModels`: to keep a clean relation between all the package, we should always be using tagged versions (raising minimum required version in top-level `Project.toml`, if necessary).  The new package registration process is quite fast, so this shouldn't be a big deal.

Move docs dependencies to Project.toml

---

.travis.yml

Could someone please add `MLJ` (and also `MLJBase` and `MLJModels`, if possible) to [Coveralls](https://coveralls.io/repos/new)?  I don't have the rights to do that, I have no idea what I'd require.
I activated Coveralls on my fork, currently coverage of `MLJ` is at 71%, which is not bad!  https://coveralls.io/github/giordano/MLJ.jl

Send code coverage to Coveralls and Codecov

---

src/tasks.jl
test/Constant.jl
test/KNN.jl
test/Transformers.jl
test/loading.jl
test/machines.jl
test/networks.jl
test/tasks.jl

With the goal of improving test coverage of the whole library, I'm starting from the file I've already worked on, `tasks.jl`.  I also started using `@test_logs`, to actually test the content of the log messages, making the tests visually less noisy and in the end more robust.
Thanks to test coverage I also realised that there were a couple of `coerce` methods that were not actually being called because of wrong signature: the default less efficient methods were being called instead, but the result was correct in any case.
The only line that is not tested is the very last one, the `unsupervised` function, I'm not sure what could be a good test for it.

Improve test coverage of tasks.jl

---

src/parameters.jl

`MLJ.get_type` will now return type of the parameter of the **instance** of the model, not of the model type definition

Change get_type implementation

---

src/resampling.jl

Fixes : #178.
This will also involve a small addition in MLJBase. Will open a PR to include that.

Add rng to resampling methods (cv and holdout)

---

Project.toml
test/Transformers.jl
test/datasets.jl
test/ensembles.jl
test/machines.jl
test/networks.jl
test/resampling.jl
test/runtests.jl
test/tuning.jl

This pull request makes the following changes:
1. Add CSV as a test-only dependency
This pull request is related to the changes in https://github.com/alan-turing-institute/MLJBase.jl/pull/24

Make CSV a test dependency

---

docs/src/tour.ipynb

The old link resulted in a 404 error.

Fix link to ipynb tour

---

docs/make.jl
docs/src/index.md
docs/src/measures.md
src/MLJ.jl
src/loading.jl
src/measures.jl
src/metadata.jl
src/model_search.jl
src/registry/src/Registry.jl
test/Constant.jl
test/KNN.jl
test/Transformers.jl
test/ensembles.jl
test/loading.jl
test/metadata.jl
test/model_search.jl
test/tuning.jl

- instead of model("PCA") just returning the handle of "PCA" (ie, (name="PCA", pkg="MultivariateStats")), it returns the whole metadata entry, eliminating need for separate "traits" method. 
- instead of only returning handles, `models()` now returns list of full metadata entries, but with pretty printing to hide details
- a query like `models() do model traits(model).is_pure_julia end` now simplifies to `models() do model.is_pure_julia end`

Simplifications to model search interface

---

README.md
docs/src/evaluating_model_performance.md
docs/src/index.md
docs/src/tuning_models.md
docs/src/working_with_tasks.md
src/loading.jl
src/model_search.jl
test/loading.jl

`@load` now returns a mode instance with default hyperparameters, as in `tree_model = @load DecisionTreeRegressor`

Have @load return an instance; update manual accordingly

---

src/composites.jl
src/networks.jl
src/utilities.jl
test/composites.jl
test/networks.jl

- If `composite` is a a learning network exported as a model, and `m = machine(composite, args...)` then `report(m)` returns the reports for each machine in the learning network, and similarly for `fitted_params(m)`. 
- `MLJ.table`, `vcat` and `hcat` now overloaded for `AbstractNode`, so that they can immediately be used in defining learning networks. For example, if `X = source(rand(20,3))` and `y=source(rand(20))` then `MLJ.table(X)` and `vcat(y, y)` both make sense and define new nodes.

report() and fitted_params() for exported learning networks

---

docs/src/index.md

Seems that some code was inadvertedly copied into the main body of the text, replacing what I believe should have been a link.

Fix copy/paste error

---

src/MLJ.jl
src/operations.jl
test/operations.jl

This allows the following:
```julia
ẑ = (W, z) |> RidgeRegressor(lambda=0.1)
ŷ = ẑ |> inverse_transform(z)
fit!(ŷ, rows=train)
ẑ[:lambda] = 5.0
fit!(ŷ, rows=train)
```
This is particularly  convenient when using this "pipeline" syntax where you may not want to write somewhere explicitly  `ridge = RidgeRegressor(lambda=0.1)` and then update `ridge.lambda`.

Direct access to hyperparameters for a node

---

Project.toml
docs/make.jl
docs/src/acceleration_and_parallelism.md
src/MLJ.jl
src/ensembles.jl
src/resampling.jl
src/tuning.jl

This PR refactors the existing distributed functionality to use dispatch so that more parallelism/acceleration methods can be easily added over time. The ideal is to expose this mechanism to the user/package author so that their very fancy parallel execution model will work just as well, without further changes to MLJ (they only need to override the appropriate methods).
This is WIP; I still need to rebase on #217 for tests (and add tests for multithreading), as well as adapt ensembles to use the same mechanism. Also, I want to find a nicer mechanism than the `parallel` keyword to trigger parallel execution.
TODO:

Broaden MLJ's parallel horizons in resampling

---

docs/src/NEWS.md
src/networks.jl
test/networks.jl

As per #288, `mean`, `median`, and `mode` methods for AbstractNode have been added. I noticed that these functions are no longer in the Base module and have been moved to the stdlib Statistics. 
Tests have also been added!

Add `mean`, `median`, and `mode` for `Nodes`

---

docs/src/evaluating_model_performance.md
src/MLJ.jl
src/resampling.jl
test/resampling.jl

resolves #108 
I have also rewritten the resampling strategy docstrings to make them more technically concise. More "instructional" documentation should go in the manual (a little less concise) and MLJTutorials (the most verbose). 
From the new docstring:
---
stratified_cv = StratifiedCV(; nfolds=6,  shuffle=false, rng=Random.GLOBAL_RNG)
Stratified cross-validation resampling strategy, for use in
`evaluate!`, `evaluate` and in tuning. Applies only to classification
problems (`OrderedFactor` or `Multiclass` targets).
train_test_pairs(stratified_cv, rows, X, y)        # X is ignored
Returns an `nfolds`-length iterator of `(train, test)` pairs of
vectors (row indices) where each `train` and `test` is a sub-vector of
`rows`. The `test` vectors are mutually exclusive and exhaust
`rows`. Each …

Stratified cross-validation

---

src/resampling.jl
test/resampling.jl
test/runtests.jl

I set the number of workers to 2 since that's what the current code in `src/resampling.jl` tests to enable parallel execution.
Closes #207

Add parallelism tests for resampling

---

docs/src/mlj_cheatsheet.md
src/ensembles.jl
src/tuning.jl

The parallel computation framework was changed to use ComputationalResources.jl in #232, but a few references to the old `parallel` keyword remain in documentation.  This pull request removes those.
Note that the second commit removes pre-existing whitespace at the end of lines in the modified files.  The actual change is in the first commit.
Cc: @jpsamaroo

Remove references to `parallel`

---

src/MLJ.jl

it turns out that we don't want to reexport this. See https://github.com/alan-turing-institute/MLJBase.jl/pull/279#issuecomment-623189385

don't export StaticTransformer

---

.github/workflows/PullRequestBaseBranch.yml

On more than one occasion, I have opened a pull request against `master` when I should I have opened it against `dev`.
This PR adds the `PullRequestBaseBranch` GitHub Action. This GitHub Action will fail if the base branch is `master` and will pass otherwise.

Create the "PullRequestBaseBranch" GitHub Action

---

src/ensembles.jl

The definition of `show` here is not only type piracy, but it overwrites the exact same method in `Random` which can cause pre-compilation to be broken in some circumstances.  The compiler throws a warning about this if one import MLJ after explicitly importing `Random`.
My vote would be to simply go along with the `show` method in `Random`, as it's really not that long
```julia
MersenneTwister(1234, (0, 1002, 0, 3))
```
Regardless, this redundant method should definitely be removed.

removed type piracy of show for MersenneTwister

---

README.md

I don't see any need for a `develop` call here. You just want to install a package from a URL.

use `add` instead of `develop` when recommending old OpenSpecFun_jll

---

.gitattributes

The package is written in pure Julia. However, the repo also includes many examples in the form of jupyter-notebooks, which is incorrectly calculated by GitHub linguist as the repo having a major portion written in the form of *.ipynb files, which is incorrect.
This is just me being pedantic but it would be a nice addition to correct this calculation. This PR aims to solve this issue.

Update linguist to better reflect the source language of the package

---

docs/src/adding_models_for_general_use.md

Was visible in the docs build log:
```
┌ Warning: undefined binding 'MLJBase.recurseive_setproperty!' in `@docs` block in src/adding_models_for_general_use.md:1209-1212
│ ```@docs
│ MLJBase.recursive_getproperty
│ MLJBase.recurseive_setproperty!
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/R2HVS/src/Expanders.jl:300
```

Fix typo in documentation

---

docs/src/tuning_models.md

In response to #822.
@ablaom, In this PR, I've tried to add an example for nested cross-validation as discussed before. You said it could be done now since https://github.com/JuliaAI/MLJTuning.jl/pull/142. However, I cannot figure out how to do it. I would expect this PR to work, but instead I get:
```
c.value = ArgumentError: You have specified an explicit iterator `models` of MLJModels and so cannot specify any `tuning` strategy except `Explicit`. Either omit the `tuning=...` specification, or specify a *single* model using `model=...` instead.
```

Document the `Explicit` tuning strategy

---

docs/src/getting_started.md

Just a small detail I noted while reading docs.

Use `isordered` instead of private CategoricalArray fields

---

docs/src/getting_started.md

Just noticed several typos in the single page.

Fix typos in Getting Started

---

ORGANIZATION.md
ROADMAP.md
docs/src/list_of_supported_models.md

I found links for MLJFlux.j are broken in some documents.
This PR fixed these broken URLs in the following way.
OLD: https://github.com/JuliaAI/MLJFlux.jl
NEW: https://github.com/FluxML/MLJFlux.jl

Fix MLJFlux.jl project URL

---

src/MLJ.jl

Fix #880 
Sorry, I tried to do it in the optimum way but as I am new to the repository and also this is my first PR to this repository, so I was little bit scared.  Once get a little bit more familiar to the codebase, I wish to come back to it. 
let me know if I made any mistake. 
@ablaom

Added recent measures to src/MLJ.jl

---

docs/src/adding_models_for_general_use.md

Adresses: https://github.com/alan-turing-institute/MLJ.jl/issues/780#issuecomment-940625847

Explain outlier detection models

---

docs/src/list_of_supported_models.md

BagOfWordsTransformer -> CountTransformer in List of Models

---

docs/src/adding_models_for_general_use.md
docs/src/composing_models.md
docs/src/transformers.md
src/MLJ.jl

Context: #901. 
Friendlier view of the addition in this PR:  https://github.com/alan-turing-institute/MLJ.jl/blob/standardize-docstrings/docs/src/adding_models_for_general_use.md#document-strings
Still to do:

Add documentation for the new model docstring standard

---

docs/src/list_of_supported_models.md

For some reason the precedent PR was not accounted for. This PR (based on dev) try again to update the names of BetaML models. From https://github.com/alan-turing-institute/MLJ.jl/issues/993 (reordered).

(re) updated model names of BetaML

---

.gitattributes

Currently, Linguist shows that the repository is 50.1% TeX meaning that the repo will be classified as a TeX repo. This PR sets `linguist-vendored` for some more files to exclude them from the stats (see [github/linguist/overrides.md](https://github.com/github/linguist/blob/master/docs/overrides.md) for more information).
In my own fork (https://github.com/rikhuijzer/MLJ.jl), this change makes the repo appear as 100% Julia.

Exclude `bib`, `md`, and `drawio` from repo stats

---

docs/src/adding_models_for_general_use.md

Minor cleanup of some mistakes in the documentation I stumbled upon when implementing a new model

Cleaned up Adding Models for General Use documentation

---

docs/src/third_party_packages.md

CatBoost.jl is in the list of supported models and the list of third-party unregistered models

Remove CatBoost.jl from third party packages

---

src/MLJ.jl

Solving #1041 by importing `fit!` and others again. In #1034, that functions were removed probably by accident.

Adding necessary exports

---

.github/workflows/ci.yml

Fixes the "silent" part of #1045 
Obviously doesn't actually fix the underlying doc failure.

CI: fix the YAML syntax for the docs job, and thus properly surface any docbuild failures

---

docs/make.jl

Removed push_preview as distracting.
Now we see in the log that the build is successful but nothing gets deployed on gh-pages, confirmed by looking at date on dev folder here: https://github.com/alan-turing-institute/MLJ.jl/tree/gh-pages (5 months ago).
I don't understand why the docs are not deploying.
@DilumAluthge

Try again to generate the documentation

---

docs/src/tuning_models.md

The links to MLJTuning.jl were pointing to github.com/FluxML/model-zoo

Fix MLJTuning.jl links

---

docs/src/adding_models_for_general_use.md

Clarify `input_scitype` for Static models

---

src/MLJ.jl

Documentation updates

---

docs/src/getting_started.md

When the command ScientificTypes.schema
is called in line 338 produce an error message
ERROR: UndefVarError: `ScientificTypes` not defined.
My suggestion is replacing line 338 by:
schema(X)

Update getting_started.md to avoid error from line 338

---

examples/lightning_tour/lightning_tour.ipynb
examples/lightning_tour/lightning_tour.jl
examples/telco/notebook.ipynb
examples/telco/notebook.jl
examples/telco/notebook.pluto.jl
examples/telco/notebook.unexecuted.ipynb
paper/paper.bib
src/MLJ.jl
test/integration.jl

Targets the `dev` branch.
Change all instances of:
1. `github.com/alan-turing-institute/` ---> `github.com/JuliaAI/`
2. `alan-turing-institute.github.io/` ---> `juliaai.github.io/`

Updates now that MLJ.jl has been moved to the JuliaAI GitHub organization

---

Project.toml
test/integration.jl

Currently it's painful to check the log for integration tests  because some models have a low bar for issuing warnings that are almost certainly irrelevant for the purposes of the integration tests. 
In this PR we suppress these warnings. We also:
- Test *all* models not in the `PATHOLOGIES` category, with models flagged using `FILTER_GIVEN_ISSUE` allowed to silently fail, unless they *pass* tests, a fact we now report in the log.  Previously these latter models were just ignored, along with `PATHOLOGIES`. 
- Reinstate some models in integration tests previously flagged in issues but now sorted
- Tidy up test code to reduce some duplication
- Move "MLJSckitLearnInterface" models in to PATHOLOGIES for now. These add a lot to overall test time. I will post an issue suggesting we might …

Suppress model-generated warnings in integration tests

---

GOVERNANCE.md

This is approximately modelled on the Flux document.
I'll leave this open for comment until at least the end of June, 2024.
I'm considering applying to make MLJ a NumFocus ["Fiscally Sponsored Project"](https://numfocus.org/projects-overview). This doesn't fund the project per se, but hopefully makes it more attractive and easier for agencies/companies to fund the project. NumFocus is a US non-profit. If there are other suggestions for achieving these goals, feel free to comment here.

Add a draft governance document

---

README.md
docs/model_docstring_tools.jl
docs/src/index.md
docs/src/learning_mlj.md

This PR adds references to the new landing page juliaml.ai into the docs and removes some redundancies created by this new page.

Integration of new landing page into docs

---

Project.toml
test/integration.jl

https://github.com/JuliaAI/MLJ.jl/issues/1152#issuecomment-3066648235

Rm SymbolicRegression from Project.toml
